name: create new branch

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout master
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Create new Branch
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git init
          git config --global user.email "ci@example.com"
          git config --global user.name "CI Action"
          git rm --cached -r * 
          if [[ ! -f .gitignore ]]; then
            # Make sure .gitignore exists
            touch .gitignore
          fi
          if ! grep -q .ci-tools .gitignore; then
            # Add .ci-tools to .gitignore
            echo -e "src\n
            .editorconfig\n
            .travis.yml\n
            .gitignore\n
            .babelrc\n
            ./images\n
            webpack.config.js\n
            bin\n
            gulpfile.js\n
            .prettierignore\n
            config.js\n
            node_modules\n
            content\n
            package.json\n
            svgpack\n
            tmp\n
            config.toml\n
            yarn.lock\n
            renovate.json\n
            !/exampleSite/config.toml\n
            !/exampleSite/content\n
            !/exampleSite/static" >> .gitignore
          fi
          git add .
          git checkout -b release
          git commit -m "Deploy from Github Actions"
          git push --force origin release
