name: create new branch

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout master
        uses: actions/checkout@v2
        with:
          ref: master

      - name: npm init
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - name: Create new Branch
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          yarn
          yarn build
          rm -rf .git
          git init
          git config --global user.email "ci@example.com"
          git config --global user.name "CI Action"
          if [[ ! -f .gitignore ]]; then
            # Make sure .gitignore exists
            touch .gitignore
          fi
          if ! grep -q .ci-tools .gitignore; then
            # Add .ci-tools to .gitignore
            echo "
          src
          .browserslistrc
          .github
          .storybook
          .gitignore
          .babelrc
          .stylelintrc.json
          webpack.config.js
          babel.config.js
          config.js
          gulpfile.js
          .prettierignore
          .prettierrc
          node_modules
          setting-site.json
          settings.js
          package.json
          yarn.lock
          renovate.json" >> .gitignore
          fi
          git add .
          git commit -m "Deploy from Github Actions"
          git push --force --quiet "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" master:release
