name: create new branch

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout master
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Pusher
        run: |
          then
            git add .
            git commit -m "github actions is pushed"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Push
        run: git push
